out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: Cora
dataset:
  format: PyG
  name: Cora
  task: node
  task_type: classification
  transductive: True
  split_mode: random
  split: [0.8, 0.1, 0.1]
  node_encoder: True
  node_encoder_name: RWSE
#   node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: DummyEdge
#   edge_encoder_num_types: 4
  edge_encoder_bn: False
posenc_LapPE:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 8
  model: DeepSet
  dim_pe: 8
  layers: 2
  raw_norm_type: none
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
#   graph_pooling: add
gt:
  layer_type: GCN+Transformer
  layers: 3
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.2
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: False
gnn:
  head: node
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
