out_dir: results
metric_best: ap
wandb:
  use: True
  project: molpcba
dataset:
  format: OGB
  name: ogbg-molpcba
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+SignNet+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_SignNet:
  enable: True
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 37  # Max graph size in molpcba is 332, but 97.1% are <= 37
  model: DeepSet
  dim_pe: 32  # Note: In original SignNet codebase dim_pe is always equal to max_freq
  layers: 8  # Num. layers in \phi model
  post_layers: 3  # Num. layers in \rho model; The original uses the same as in \phi
  phi_hidden_dim: 64
  phi_out_dim: 64
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 20
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 256
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Transformer
  layers: 5
  n_heads: 4
  dim_hidden: 384  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.2
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: default  # san_graph
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 384  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  batch_accumulation: 2
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
